### PR TITLE
allow custom HTTP headers to be sent with each HTTP verb function

### PR DESCRIPTION
**Pull request by twelve17**
Hi there,

What do you think about adding this implementation of the "add subscriber" API call?  

https://dev.fitbit.com/docs/subscriptions/#adding-a-subscription

It's a bit of a one off, because the API call takes an optional HTTP header, so I had to add an optional extra parameter to the `post` function, to allow the additional header.   Let me know your thoughts.

Thanks!

Alex

### CODE REVIEW

**Comment by twelve17** [comment]
Actually, I just found there are "delete" and "list" APIs for subscriptions as well, and they all take an optional header. I wonder if it would be a more generic solution to just allow extra headers on the various HTTP verb methods instead of implementing specific APIs?

**Comment by mbmccormick** [comment]
I think it would be best to do what you suggest -- allow extra headers on each HTTP verb method instead of specific APIs for subscriptions. I am able to use the existing methods to manage subscriptions for Fitminder here: https://github.com/mbmccormick/fitminder/blob/master/app/fitbit.js. Granted, that's not using the header and the existing methods wouldn't allow me to do that even if I wanted to.

I think headers is the way to go. Thanks for your contribution! 😄

**Comment by twelve17** [comment]
Ok, I've updated the code to just do the header approach. Let me know what you think.  

Thanks!

**Comment by mbmccormick** [comment]
Awesome, looks good. Thank you!

**Comment by mbmccormick** [comment]
Published to npm in version 2.0.4. Thanks again!

**Pull request merged**
