### PR TITLE
Support 'prompt' and 'state' parameters to the client.getAuthorizeUrl method.

### PR DESCRIPTION
**Pull request by foundling**
Hi again, 

I added 'prompt' and 'state' parameters to the client.getAuthorizeUrl method and updated the documentation to reflect that.

Also, I was thinking that the argument list is getting a little long for this method.  I didn't want to diverge from the general style so far, but maybe the methods could be revised to accept an options object as the last parameter for optional arguments like 'prompt' and 'state'?

Cheers,
Alex

### CODE REVIEW

**Comment by foundling** [comment]
Hi, just checking back in on this. I'd really love to be able to force any previously logged-in user out of FitBit before authenticating a new user, which is what supporting the 'prompt' parameter does. 

Thanks,
Alex

**Comment by mbmccormick** [comment]
Sorry for the delay, this looks great. And thanks for fixing the casing on `refreshAccessToken` -- nothing drives me crazier! 👍

**Comment by mbmccormick** [comment]
Published to npm in version 2.0.5. Thanks again!

**Comment by foundling** [comment]
No problem Matt, thanks for merging! This library has been really useful to me.

**Pull request merged**
